konentung/OnlineProgrammingPlatform

.gitignore
=> feature-新增gitignore

posts/forms.py, templates/questions/question_peer_assessment.html, templates/questions/question_peer_assessment_list.html
1. 修改 question_peer_assessment_list 頁面排版。
2. 將 <a> 放在最外層直接將 <a> 標籤包裹整個 list-group-item 的內容，使整個區塊都變成可點擊範圍。
3. 修改 question_peer_assessment 頁面排版。
4. 將題目的程式碼使用 pre 和 code 標籤來格式化程式碼。
5. 修改 forms.py 的 PeerReviewForm 類別，style': 'text-align-last: center，將評分區塊中的數字置中。
6. 修改 question_peer_assessment 出題人姓名
=> feature-create-peer_assessment頁面

posts/forms.py, templates/questions/question_peer_assessment.html
=> bugfix-修正不能查看裡史紀錄的錯誤

posts/forms.py
=> bugfix-修正不能查看歷史紀錄的錯誤

OnlineProgrammingPlatform/urls.py, posts/forms.py, posts/views.py, templates/close.html, templates/maintenance.html
1.建立網頁功能的物件去處理是否啟用功能
2.清理forms.py中無用的空行
3.建立不啟用及維護中的頁面
4.再views.py中放頁面重新導向的程式以及頁面功能啟用的判斷
=> feature-網頁功能開發鎖定設定

OnlineProgrammingPlatform/urls.py, posts/views.py, templates/base.html, templates/questions/ranking.html
1.新增排行的的views
2.新增排行榜的HTML
3.新增查看排行榜的路由
=> CODINGPJ-8 排行榜程式碼

OnlineProgrammingPlatform/urls.py, posts/views.py, templates/base.html, templates/questions/question_create.html, templates/user_dashboard.html
1. 新增學生個人頁面
2. 計算學生出題數、解題數、評分題目數量
=> CODINGPJ-15 新增個人頁面

posts/forms.py, posts/views.py, templates/questions/question_peer_assessment.html
1.新增已作答題目才會出現在評分中
2.新增評分不可為0的規則
3.新增可以取消送出的功能，避免誤觸送出導致無法修改
=> feature-根據已作答的題目開放可以評分的題目

OnlineProgrammingPlatform/urls.py, posts/views.py, templates/questions/question_review.html, templates/questions/user_question_history_list.html
=> CODINGPJ-17 查看自己出題的回饋頁面

staticfiles/css/search.css, templates/index.html
1. 新增篩選器的javascipt
2. 新增分類的HTML
=> CODINGPJ-19 新增用難易度做分類的選擇器

templates/questions/question_assignment_list.html
1. 新增學生難易度選擇的區塊
2. 新增javascript動態切換選擇的難易度
=> CODINGPJ-21 學生作業區分類

templates/questions/ranking.html
1. 新增學生解題的排行榜
2. 修改本排行榜的html讓使用者可以選擇要看哪個排行榜
=> CODINGPJ-22 學生解題排行榜

posts/views.py, templates/base.html, templates/questions/ranking.html
=> CODINGPJ-20 學生出題排行榜修正

posts/views.py
1. 解決學生在解題可以重複送出的問題
2. 解決學生未解題卻可以建立實例的問題
=> CODINGPJ-23 學生計分問題

posts/views.py
=> CODINGPJ-24 排行榜排名顯示錯誤

templates/user_dashboard.html
1.將 "學生資訊" 標題從卡片抽出為整個頁面的標題
2.將學生資料重新使用card布局，搭配陰影和圓角，此為主要更動。
3.保持其他區塊（建立的題目、作答記錄、評分記錄）的排列邏輯不變，小微調。
=> CODINGPJ-28 user_dashboard頁面

templates/questions/question_detail.html
1.卡片樣式： 使用Bootstrap的card和card-body類將問題描述、評論和表單區分開來，提供更好的視覺層次結構。 
2.標題和子標題： 標題和子標題使用了card-title和card-subtitle類，並增加了text-muted類來稍微改善可讀性和美觀度。
3.評論區： 評論區也被包裹在卡片組件內，使其看起來較為統一整潔。
4.表單樣式： 在表單輸入區域增加了form-control類，使輸入框看起來更整齊統一，並改進了錯誤信息的顯示方式。
=> CODINGPJ-2 detail頁面

OnlineProgrammingPlatform/settings.py
1. 設定CSRF_TOKEN
2. 重新設定資料庫env
3. 設定快取位置
=> CODINGPJ-34 設定CSRF_TOKEN

staticfiles/js/answer_submit.js, staticfiles/js/codespace.js, staticfiles/js/question_card.js, staticfiles/js/question_submit.js, staticfiles/js/question_update.js, staticfiles/js/ranking.js, staticfiles/js/review_submit.js
=> CODINGPJ-34 靜態檔案處理

templates/base.html
=> CODINGPJ-32 base頁面重設

templates/questions/question_answer.html
=> CODINGPJ-29 answer頁面顯示問題

OnlineProgrammingPlatform/urls.py, posts/admin.py, posts/forms.py, posts/models.py, posts/views.py, static/js/chat_bot.js, staticfiles/js/chat_bot.js, templates/base.html, templates/chat.html
1. 資料庫新增紀錄回答的欄位
2. 新增Chat_view作後端的判讀，處理OPENAI的request
3. 新增前端的html
4. 新增對應的js
=> CODINGPJ-25 在網頁中新增ChatBot

games/views.py, static/js/game.js
1. 移除回傳400導致遊戲卡住的問題
2. 未來可能還會修改邏輯所以沒有拿掉所有的400
=> CODINGPJ-44 移除物件碰撞卡住的問題

GamingWeb/settings.py
=> CODINGPJ-45 雲端部屬

static/css/game.css
1. 變更紅色裂縫作答畫面:選項樣式及配置更改、內容放大
2. 變更藍色裂縫作答畫面: 輸入框樣式及配置更改、送出按鈕增加變色動態效果
3. 對話框文字至中、透明度調高
=> CODINGPJ-51 回答問題的前段介面修改

GamingWeb/urls.py, games/views.py, static/js/game.js, static/js/utils.js, templates/games/game.html
1. 移除開頭的對話模式，修改成播放動畫
2. 設定重製遊戲到displaygameover函式中，讓遊戲可以重新設定
3. startflow中多設定一個判斷式讓我的幕間動畫可以插入
4. 新增播放動畫和取得url的api的function
=> CODINGPJ-59 幕間放入影片
